//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 数据字典表，将有可能发生变化或者有多种分类的字段内容存到本表中，根节点的name要保证唯一
    /// </summary>
    public partial class OT_Dic
    {
        public OT_Dic()
        {
            this.OT_ExportHis = new HashSet<OT_ExportHis>();
            this.OT_HDayConfig = new HashSet<OT_HDayConfig>();
            this.OT_HDayConfig1 = new HashSet<OT_HDayConfig>();
        }
    
    	/// <summary>
    	/// 标识
    	/// </summary>
        public int Id { get; set; }
    	/// <summary>
    	/// 
    	/// </summary>
        public int Type { get; set; }
    	/// <summary>
    	/// 名称
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// 父标识，0表示根节点
    	/// </summary>
        public Nullable<int> Belong { get; set; }
    	/// <summary>
    	/// 排序，有时候需要对类型进行排序,需要时也可用来作为级别的划分
    	/// </summary>
        public Nullable<int> Rank { get; set; }
    	/// <summary>
    	/// 备注
    	/// </summary>
        public string Rek { get; set; }
    	/// <summary>
    	/// 删除标识
    	/// </summary>
        public Nullable<byte> IsDelete { get; set; }
    
        public virtual ICollection<OT_ExportHis> OT_ExportHis { get; set; }
        public virtual ICollection<OT_HDayConfig> OT_HDayConfig { get; set; }
        public virtual ICollection<OT_HDayConfig> OT_HDayConfig1 { get; set; }
    }
}
