//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 收费站数据接收失败记录表
    /// </summary>
    public partial class OT_ErrorStation
    {
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 收费站ID
    	/// </summary>
        public int StaID { get; set; }
    	/// <summary>
    	/// 收费站名称
    	/// </summary>
        public string StaName { get; set; }
    	/// <summary>
    	/// 统计时间
    	/// </summary>
        public System.DateTime CalcuTime { get; set; }
    	/// <summary>
    	/// 时间段
    	/// </summary>
        public Nullable<byte> HourPer { get; set; }
    }
}
