//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 假期报送配置表
    /// </summary>
    public partial class OT_HDayConfig
    {
    	/// <summary>
    	/// 标识
    	/// </summary>
        public int Id { get; set; }
    	/// <summary>
    	/// 报表名称\配置项，该字段名称存储在OT_Dic表中，根节点条件为  name=‘配置项’  
    	/// </summary>
        public string ConfigName { get; set; }
    	/// <summary>
    	/// 假期名称，该字段名称存储在OT_Dic表中，根节点条件为  name=‘假期名称’  
    	/// </summary>
        public Nullable<int> HDayId { get; set; }
    	/// <summary>
    	/// 假期开始时间
    	/// </summary>
        public Nullable<System.DateTime> HDayStart { get; set; }
    	/// <summary>
    	/// 假期截止时间，截止时间要比开始时间大
    	/// </summary>
        public Nullable<System.DateTime> HDayEnd { get; set; }
    	/// <summary>
    	/// 同比开始时间
    	/// </summary>
        public Nullable<System.DateTime> CompStart { get; set; }
    	/// <summary>
    	/// 同比截止时间，截止时间要比开始时间大
    	/// </summary>
        public Nullable<System.DateTime> CompEnd { get; set; }
    	/// <summary>
    	/// 预测日期
    	/// </summary>
        public Nullable<System.DateTime> ForeDate { get; set; }
    	/// <summary>
    	/// 预测浮动百分比
    	/// </summary>
        public Nullable<int> ForeFloat { get; set; }
    	/// <summary>
    	/// 报表备注，如有涉及到填表人、联系电话、手机时，需要在这三个信息之家加逗号隔开保存，读取时需要进行解析
    	/// </summary>
        public string RptRemark { get; set; }
    	/// <summary>
    	/// 校正浮动百分比
    	/// </summary>
        public Nullable<int> CheckFloat { get; set; }
    	/// <summary>
    	/// 配置显示类型9	默认假期名称	 10	每日报送 11	北京交通委	 12		北京市路政局	 13		北京旅游委	 14		北京交通部门	 15		北京交通委	 16		天津交通部门	 17	天津高速处
    	/// </summary>
        public int Type { get; set; }
    	/// <summary>
    	/// 可配置项，记录当前数据哪些配置项可配置
    	/// </summary>
        public string ConfigItem { get; set; }
    
        public virtual OT_Dic OT_Dic { get; set; }
        public virtual OT_Dic OT_Dic1 { get; set; }
    }
}
