//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 系统日志表
    /// </summary>
    public partial class OT_Log
    {
    	/// <summary>
    	/// 标识
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 角色名称
    	/// </summary>
        public string RoleName { get; set; }
    	/// <summary>
    	/// 操作时间
    	/// </summary>
        public System.DateTime LogDate { get; set; }
    	/// <summary>
    	/// 日志类型
    	/// </summary>
        public string Type { get; set; }
    	/// <summary>
    	/// 操作明细描述
    	/// </summary>
        public string Describe { get; set; }
    	/// <summary>
    	/// 信息级别
    	/// </summary>
        public Nullable<int> Rank { get; set; }
    	/// <summary>
    	/// 报表名称
    	/// </summary>
        public string RptName { get; set; }
    	/// <summary>
    	/// 操作用户名称
    	/// </summary>
        public string UserName { get; set; }
    }
}
