//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 角色表
    /// </summary>
    public partial class OT_Role
    {
        public OT_Role()
        {
            this.OT_UserRole = new HashSet<OT_UserRole>();
        }
    
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 角色名称
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// 层级，用来区分角色的层级，该字段名称存储在DS_Help表中，根节点条件为  name=‘角色级别’  
    	/// </summary>
        public int Rank { get; set; }
    	/// <summary>
    	/// 是删除，0表示未删除，1表示删除
    	/// </summary>
        public byte IsDelete { get; set; }
    
        public virtual ICollection<OT_UserRole> OT_UserRole { get; set; }
    }
}
