//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 收费站基本信息表
    /// </summary>
    public partial class OT_Station
    {
    	/// <summary>
    	/// 标识
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 编号
    	/// </summary>
        public string Num { get; set; }
    	/// <summary>
    	/// 名称
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// 入口方向-0：出境，1：入境（进境）
    	/// </summary>
        public int InDir { get; set; }
    	/// <summary>
    	/// 出口方向-0：出境，1：入境（进境）
    	/// </summary>
        public int OutDir { get; set; }
    	/// <summary>
    	///  1:北京段2：河北，3：天津,泗村店、杨村、宜兴埠、金钟路、机场、空港、塘沽西、塘沽 
    	/// </summary>
        public int District { get; set; }
    	/// <summary>
    	/// 已删除，0表示未删除，1表示已删除
    	/// </summary>
        public byte IsDelete { get; set; }
    	/// <summary>
    	/// 单车费额
    	/// </summary>
        public double Charge { get; set; }
    }
}
