//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户表
    /// </summary>
    public partial class OT_User
    {
        public OT_User()
        {
            this.OT_UserRole = new HashSet<OT_UserRole>();
        }
    
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 登录名
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// 登录密码
    	/// </summary>
        public string Password { get; set; }
    	/// <summary>
    	/// 是删除，0表示未删除，1表示删除
    	/// </summary>
        public byte IsDelete { get; set; }
    
        public virtual ICollection<OT_UserRole> OT_UserRole { get; set; }
    }
}
