//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户角色关系表，用来使用户和角色建立关系
    /// </summary>
    public partial class OT_UserRole
    {
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 用户标识
    	/// </summary>
        public System.Guid UserId { get; set; }
    	/// <summary>
    	/// 角色标识
    	/// </summary>
        public System.Guid RoleId { get; set; }
    	/// <summary>
    	/// 已删除，0表示未删除，1表示删除
    	/// </summary>
        public byte IsDelete { get; set; }
    
        public virtual OT_Role OT_Role { get; set; }
        public virtual OT_User OT_User { get; set; }
    }
}
