//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 黄金周京津塘高速公路交通量及客运情况统计表(7)
    /// </summary>
    public partial class RP_AADTAndTransCalcu
    {
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 进京方向交通量
    	/// </summary>
        public Nullable<double> EnTra { get; set; }
    	/// <summary>
    	/// 进京方向客车数
    	/// </summary>
        public Nullable<double> EnCar { get; set; }
    	/// <summary>
    	/// 进京方向旅客量
    	/// </summary>
        public Nullable<double> EnTrav { get; set; }
    	/// <summary>
    	/// 出京方向交通量
    	/// </summary>
        public Nullable<double> ExTra { get; set; }
    	/// <summary>
    	/// 出京方向客车数
    	/// </summary>
        public Nullable<double> ExCar { get; set; }
    	/// <summary>
    	/// 出京方向旅客量
    	/// </summary>
        public Nullable<double> ExTrav { get; set; }
    	/// <summary>
    	/// 统计时间
    	/// </summary>
        public System.DateTime CalcuTime { get; set; }
    	/// <summary>
    	/// 创建人
    	/// </summary>
        public string CrtBy { get; set; }
    	/// <summary>
    	/// 创建日期
    	/// </summary>
        public System.DateTime CrtDate { get; set; }
    	/// <summary>
    	/// 修改人
    	/// </summary>
        public string UpdBy { get; set; }
    	/// <summary>
    	/// 修改日期
    	/// </summary>
        public Nullable<System.DateTime> UpdDate { get; set; }
    	/// <summary>
    	/// 数据状态1为已修改，0为未修改
    	/// </summary>
        public string State { get; set; }
    }
}
