//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 出入境车辆数日报表(5.6)
    /// </summary>
    public partial class RP_EnEx
    {
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 入境小型客车数
    	/// </summary>
        public Nullable<double> EnSmaCar { get; set; }
    	/// <summary>
    	/// 入境其他客车数
    	/// </summary>
        public Nullable<double> EnOthCar { get; set; }
    	/// <summary>
    	/// 入境货车数
    	/// </summary>
        public Nullable<double> EnTruk { get; set; }
    	/// <summary>
    	/// 入境绿色通道数
    	/// </summary>
        public Nullable<double> EnGre { get; set; }
    	/// <summary>
    	/// 出境小型客车数
    	/// </summary>
        public Nullable<double> ExSmaCar { get; set; }
    	/// <summary>
    	/// 出境其他客车数
    	/// </summary>
        public Nullable<double> ExOthCar { get; set; }
    	/// <summary>
    	/// 出境货车数
    	/// </summary>
        public Nullable<double> ExTruk { get; set; }
    	/// <summary>
    	/// 出境绿色通道数
    	/// </summary>
        public Nullable<double> ExGre { get; set; }
    	/// <summary>
    	/// 统计站类型： 1：(北京段)大羊坊，马驹桥东，马驹桥西，采育 33：泗村店 
    	/// </summary>
        public Nullable<int> StaType { get; set; }
    	/// <summary>
    	/// 统计时间
    	/// </summary>
        public System.DateTime CalcuTime { get; set; }
    	/// <summary>
    	/// 创建人
    	/// </summary>
        public string CrtBy { get; set; }
    	/// <summary>
    	/// 创建日期
    	/// </summary>
        public Nullable<System.DateTime> CrtDate { get; set; }
    	/// <summary>
    	/// 修改人
    	/// </summary>
        public string UpdBy { get; set; }
    	/// <summary>
    	/// 修改日期
    	/// </summary>
        public Nullable<System.DateTime> UpdDate { get; set; }
    	/// <summary>
    	/// 数据状态1为已修改，0为未修改
    	/// </summary>
        public string State { get; set; }
    }
}
