//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 假期流量表(11.12)
    /// </summary>
    public partial class RP_HDayAADT
    {
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 杨村站流量
    	/// </summary>
        public Nullable<double> YC { get; set; }
    	/// <summary>
    	/// 宜兴埠东站流量
    	/// </summary>
        public Nullable<double> YXBD { get; set; }
    	/// <summary>
    	/// 宜兴埠西站流量
    	/// </summary>
        public Nullable<double> YXBX { get; set; }
    	/// <summary>
    	/// 金钟路站流量
    	/// </summary>
        public Nullable<double> JZL { get; set; }
    	/// <summary>
    	/// 机场站流量
    	/// </summary>
        public Nullable<double> JC { get; set; }
    	/// <summary>
    	/// 空港经济区站流量
    	/// </summary>
        public Nullable<double> KG { get; set; }
    	/// <summary>
    	/// 塘沽西站流量
    	/// </summary>
        public Nullable<double> TGX { get; set; }
    	/// <summary>
    	/// 塘沽西分站流量
    	/// </summary>
        public Nullable<double> TGXF { get; set; }
    	/// <summary>
    	/// 塘沽北站流量
    	/// </summary>
        public Nullable<double> TGB { get; set; }
    	/// <summary>
    	/// 同期总流量
    	/// </summary>
        public Nullable<double> SameSum { get; set; }
    	/// <summary>
    	/// 同比增幅
    	/// </summary>
        public Nullable<double> CompGrow { get; set; }
    	/// <summary>
    	/// 出口流量
    	/// </summary>
        public Nullable<double> Out { get; set; }
    	/// <summary>
    	/// 统计时间
    	/// </summary>
        public Nullable<System.DateTime> CalcuTime { get; set; }
    	/// <summary>
    	/// 创建人
    	/// </summary>
        public string CrtBy { get; set; }
    	/// <summary>
    	/// 创建日期
    	/// </summary>
        public System.DateTime CrtDate { get; set; }
    	/// <summary>
    	/// 修改人
    	/// </summary>
        public string UpdBy { get; set; }
    	/// <summary>
    	/// 修改日期
    	/// </summary>
        public Nullable<System.DateTime> UpdDate { get; set; }
    	/// <summary>
    	/// 数据状态：1为已修改，0为未修改
    	/// </summary>
        public string State { get; set; }
    	/// <summary>
    	/// 
    	/// </summary>
        public Nullable<double> Sum { get; set; }
    }
}
