//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 假期高速公路交通流量统计表(18)
    /// </summary>
    public partial class RP_HDayAADTSta
    {
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 出京自然交通辆
    	/// </summary>
        public Nullable<double> ExNat { get; set; }
    	/// <summary>
    	/// 进京自然交通辆
    	/// </summary>
        public Nullable<double> EnNat { get; set; }
    	/// <summary>
    	/// 出京当量交通辆
    	/// </summary>
        public Nullable<double> ExEqu { get; set; }
    	/// <summary>
    	/// 进京当量交通辆
    	/// </summary>
        public Nullable<double> EnEqu { get; set; }
    	/// <summary>
    	/// 拥挤度
    	/// </summary>
        public Nullable<double> CrowDeg { get; set; }
    	/// <summary>
    	/// 小型车出京
    	/// </summary>
        public Nullable<double> SmaEx { get; set; }
    	/// <summary>
    	/// 小型车进京
    	/// </summary>
        public Nullable<double> SmaEn { get; set; }
    	/// <summary>
    	/// 中型车出京
    	/// </summary>
        public Nullable<double> MedEx { get; set; }
    	/// <summary>
    	/// 中型车进京
    	/// </summary>
        public Nullable<double> MedEn { get; set; }
    	/// <summary>
    	/// 大型车出京
    	/// </summary>
        public Nullable<double> LarEx { get; set; }
    	/// <summary>
    	/// 大型车进京
    	/// </summary>
        public Nullable<double> LarEn { get; set; }
    	/// <summary>
    	/// 重型车出京
    	/// </summary>
        public Nullable<double> HeaEx { get; set; }
    	/// <summary>
    	/// 重型车进京
    	/// </summary>
        public Nullable<double> HeaEn { get; set; }
    	/// <summary>
    	/// 超大型车出京
    	/// </summary>
        public Nullable<double> SupEx { get; set; }
    	/// <summary>
    	/// 超大型车进京
    	/// </summary>
        public Nullable<double> SupEn { get; set; }
    	/// <summary>
    	/// 进出京货车数量
    	/// </summary>
        public Nullable<double> EnExTrukNum { get; set; }
    	/// <summary>
    	/// 客车货车比例
    	/// </summary>
        public Nullable<double> CarTrukPer { get; set; }
    	/// <summary>
    	/// 进出京大货车以上车型的数量
    	/// </summary>
        public Nullable<double> SupTruNum { get; set; }
    	/// <summary>
    	/// 大货车以上占货车交通量比例
    	/// </summary>
        public Nullable<double> SupTruPer { get; set; }
    	/// <summary>
    	/// 统计时间
    	/// </summary>
        public System.DateTime CalcuTime { get; set; }
    	/// <summary>
    	/// 创建人
    	/// </summary>
        public string CrtBy { get; set; }
    	/// <summary>
    	/// 创建日期
    	/// </summary>
        public System.DateTime CrtDate { get; set; }
    	/// <summary>
    	/// 修改人
    	/// </summary>
        public string UpdBy { get; set; }
    	/// <summary>
    	/// 修改日期
    	/// </summary>
        public Nullable<System.DateTime> UpdDate { get; set; }
    	/// <summary>
    	/// 数据状态：1为已修改，0为未修改
    	/// </summary>
        public string State { get; set; }
    	/// <summary>
    	/// 1:交调观测点1，2：交调观测点2，3：交调观测点3，4：收费站马驹桥，5收费站大羊坊
    	/// </summary>
        public int LineType { get; set; }
    }
}
