//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 0-24小时交通量表(13.14)
    /// </summary>
    public partial class RP_HourAADT
    {
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 大羊坊出京入通量
    	/// </summary>
        public Nullable<double> Dyf_ExIn { get; set; }
    	/// <summary>
    	/// 大羊坊进京出通量
    	/// </summary>
        public Nullable<double> Dyf_EnOut { get; set; }
    	/// <summary>
    	/// 马驹桥东进京入通量
    	/// </summary>
        public Nullable<double> Mjqd_EnIn { get; set; }
    	/// <summary>
    	/// 马驹桥东进京出通量
    	/// </summary>
        public Nullable<double> Mjqd_EnOut { get; set; }
    	/// <summary>
    	/// 马驹桥西出京入通量
    	/// </summary>
        public Nullable<double> Mjqx_ExIn { get; set; }
    	/// <summary>
    	/// 马驹桥西进京出通量
    	/// </summary>
        public Nullable<double> Mjqx_EnOut { get; set; }
    	/// <summary>
    	/// 采育出京入通量
    	/// </summary>
        public Nullable<double> Cy_ExIn { get; set; }
    	/// <summary>
    	/// 采育进京出通量
    	/// </summary>
        public Nullable<double> Cy_EnOut { get; set; }
    	/// <summary>
    	/// 时间段
    	/// </summary>
        public byte HourPer { get; set; }
    	/// <summary>
    	/// 统计日期
    	/// </summary>
        public System.DateTime CalcuTime { get; set; }
    	/// <summary>
    	/// 创建人
    	/// </summary>
        public string CrtBy { get; set; }
    	/// <summary>
    	/// 创建日期
    	/// </summary>
        public Nullable<System.DateTime> CrtDate { get; set; }
    	/// <summary>
    	/// 修改人
    	/// </summary>
        public string UpdBy { get; set; }
    	/// <summary>
    	/// 修改日期
    	/// </summary>
        public Nullable<System.DateTime> UpdDate { get; set; }
    	/// <summary>
    	/// 数据状态：1为已修改，0为未修改
    	/// </summary>
        public string State { get; set; }
    }
}
