//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.DAL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 交通自然流量（含免费）统计日报表(15.16.17)
    /// </summary>
    public partial class RP_NatSta
    {
    	/// <summary>
    	/// 标识列
    	/// </summary>
        public System.Guid Id { get; set; }
    	/// <summary>
    	/// 日交通量合计
    	/// </summary>
        public Nullable<double> Sum { get; set; }
    	/// <summary>
    	/// 进京方向日交通量
    	/// </summary>
        public Nullable<double> EnNum { get; set; }
    	/// <summary>
    	/// 出京方向日交通量
    	/// </summary>
        public Nullable<double> ExNum { get; set; }
    	/// <summary>
    	/// 统计报表类型：1：北京段)大羊坊，马驹桥东，马驹桥西，采育,15:大羊坊站
    	/// </summary>
        public Nullable<int> StaType { get; set; }
    	/// <summary>
    	/// 时间段
    	/// </summary>
        public Nullable<byte> HourPer { get; set; }
    	/// <summary>
    	/// 创建人
    	/// </summary>
        public string CrtBy { get; set; }
    	/// <summary>
    	/// 创建日期
    	/// </summary>
        public Nullable<System.DateTime> CrtDate { get; set; }
    	/// <summary>
    	/// 修改人
    	/// </summary>
        public string UpdBy { get; set; }
    	/// <summary>
    	/// 修改日期
    	/// </summary>
        public Nullable<System.DateTime> UpdDate { get; set; }
    	/// <summary>
    	/// 运行状况
    	/// </summary>
        public string RunStae { get; set; }
    	/// <summary>
    	/// 数据状态：1为已修改，0为未修改
    	/// </summary>
        public string State { get; set; }
    	/// <summary>
    	/// 备注
    	/// </summary>
        public string Rek { get; set; }
    	/// <summary>
    	/// 数据日期
    	/// </summary>
        public System.DateTime CalcuTime { get; set; }
    }
}
