//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wttech.DataSubmitted.Common.Resources.SystemConst", typeof(SystemConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正 的本地化字符串。
        /// </summary>
        public static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预测 的本地化字符串。
        /// </summary>
        public static string Forecast {
            get {
                return ResourceManager.GetString("Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿色通道 的本地化字符串。
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入口 的本地化字符串。
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string LoginOut {
            get {
                return ResourceManager.GetString("LoginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它客车 的本地化字符串。
        /// </summary>
        public static string OtherCar {
            get {
                return ResourceManager.GetString("OtherCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出口 的本地化字符串。
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计 的本地化字符串。
        /// </summary>
        public static string ReportCount {
            get {
                return ResourceManager.GetString("ReportCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整体报表导出 的本地化字符串。
        /// </summary>
        public static string ReportName0 {
            get {
                return ResourceManager.GetString("ReportName0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费公路数据汇总表 的本地化字符串。
        /// </summary>
        public static string ReportName1 {
            get {
                return ResourceManager.GetString("ReportName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ****年**假期进出京交通量表（北京段） 的本地化字符串。
        /// </summary>
        public static string ReportName10 {
            get {
                return ResourceManager.GetString("ReportName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天津市高速公路支队****年**假期重点收费站流量表（出口+入口） 的本地化字符串。
        /// </summary>
        public static string ReportName11 {
            get {
                return ResourceManager.GetString("ReportName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天津市高速公路支队****年**假期流量表（出口） 的本地化字符串。
        /// </summary>
        public static string ReportName12 {
            get {
                return ResourceManager.GetString("ReportName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0-24时各高速公路各收费站分方向出入口小时交通量（*月**日） 的本地化字符串。
        /// </summary>
        public static string ReportName13 {
            get {
                return ResourceManager.GetString("ReportName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 各高速公路各收费站出口小时交通量 的本地化字符串。
        /// </summary>
        public static string ReportName14 {
            get {
                return ResourceManager.GetString("ReportName14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交通自然流量（含免费）统计日报表（小时数据） 的本地化字符串。
        /// </summary>
        public static string ReportName15 {
            get {
                return ResourceManager.GetString("ReportName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交通自然流量（含免费）统计日报表（小时数据）--大羊坊 的本地化字符串。
        /// </summary>
        public static string ReportName16 {
            get {
                return ResourceManager.GetString("ReportName16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交通自然流量（含免费）统计日报表 的本地化字符串。
        /// </summary>
        public static string ReportName17 {
            get {
                return ResourceManager.GetString("ReportName17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 **假期高速公路交通流量统计表 的本地化字符串。
        /// </summary>
        public static string ReportName18 {
            get {
                return ResourceManager.GetString("ReportName18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费公路数据日报表 的本地化字符串。
        /// </summary>
        public static string ReportName2 {
            get {
                return ResourceManager.GetString("ReportName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 京沪高速大羊坊收费站数据日报表 的本地化字符串。
        /// </summary>
        public static string ReportName3 {
            get {
                return ResourceManager.GetString("ReportName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重要运输通道主线收费站数据日报表 的本地化字符串。
        /// </summary>
        public static string ReportName4 {
            get {
                return ResourceManager.GetString("ReportName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重点城市出入境车辆数日报表 的本地化字符串。
        /// </summary>
        public static string ReportName5 {
            get {
                return ResourceManager.GetString("ReportName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重点城市出入境车辆数日报表 的本地化字符串。
        /// </summary>
        public static string ReportName6 {
            get {
                return ResourceManager.GetString("ReportName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ****年“**”黄金周京津塘高速公路交通量及客运情况统计表 的本地化字符串。
        /// </summary>
        public static string ReportName7 {
            get {
                return ResourceManager.GetString("ReportName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ****年**假期交通量统计表 的本地化字符串。
        /// </summary>
        public static string ReportName8 {
            get {
                return ResourceManager.GetString("ReportName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费公路运行情况 的本地化字符串。
        /// </summary>
        public static string ReportName9 {
            get {
                return ResourceManager.GetString("ReportName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 京津塘高速 的本地化字符串。
        /// </summary>
        public static string RoadName {
            get {
                return ResourceManager.GetString("RoadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 京沪 的本地化字符串。
        /// </summary>
        public static string RoadName2 {
            get {
                return ResourceManager.GetString("RoadName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 京沪高速（北京段） 的本地化字符串。
        /// </summary>
        public static string RoadName3 {
            get {
                return ResourceManager.GetString("RoadName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小型客车 的本地化字符串。
        /// </summary>
        public static string SmallCar {
            get {
                return ResourceManager.GetString("SmallCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大羊坊 的本地化字符串。
        /// </summary>
        public static string TollStaName {
            get {
                return ResourceManager.GetString("TollStaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货车 的本地化字符串。
        /// </summary>
        public static string Truk {
            get {
                return ResourceManager.GetString("Truk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
