//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wttech.DataSubmitted.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TipInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipInfo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wttech.DataSubmitted.Common.Resources.TipInfo", typeof(TipInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败 的本地化字符串。
        /// </summary>
        public static string AddFaile {
            get {
                return ResourceManager.GetString("AddFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名为历史曾用名，不能重复使用！ 的本地化字符串。
        /// </summary>
        public static string AddFaileHasDelUser {
            get {
                return ResourceManager.GetString("AddFaileHasDelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已被使用！ 的本地化字符串。
        /// </summary>
        public static string AddFaileHasUser {
            get {
                return ResourceManager.GetString("AddFaileHasUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败，请选择角色! 的本地化字符串。
        /// </summary>
        public static string AddFaileSelectRole {
            get {
                return ResourceManager.GetString("AddFaileSelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败，请输入用户名! 的本地化字符串。
        /// </summary>
        public static string AddFaileSelectUser {
            get {
                return ResourceManager.GetString("AddFaileSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出失败，所选范围内暂无报表可供批量导出！ 的本地化字符串。
        /// </summary>
        public static string BatchExportFail {
            get {
                return ResourceManager.GetString("BatchExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正失败！ 的本地化字符串。
        /// </summary>
        public static string CalibrationFaile {
            get {
                return ResourceManager.GetString("CalibrationFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正失败，参考日期不合理！ 的本地化字符串。
        /// </summary>
        public static string CalibrationFaileDate {
            get {
                return ResourceManager.GetString("CalibrationFaileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正失败，校正时间段不合理！ 的本地化字符串。
        /// </summary>
        public static string CalibrationFaileHour {
            get {
                return ResourceManager.GetString("CalibrationFaileHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正失败，无假期配置信息！ 的本地化字符串。
        /// </summary>
        public static string CalibrationFaileNoConfig {
            get {
                return ResourceManager.GetString("CalibrationFaileNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正失败，校正日期无数据！ 的本地化字符串。
        /// </summary>
        public static string CalibrationFaileNoData {
            get {
                return ResourceManager.GetString("CalibrationFaileNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正失败，参考日期无数据！ 的本地化字符串。
        /// </summary>
        public static string CalibrationFaileRefNoData {
            get {
                return ResourceManager.GetString("CalibrationFaileRefNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正失败，参考日期范围和校正日期范围不相同！ 的本地化字符串。
        /// </summary>
        public static string CalibrationRangeFaile {
            get {
                return ResourceManager.GetString("CalibrationRangeFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正成功！ 的本地化字符串。
        /// </summary>
        public static string CalibrationSuccess {
            get {
                return ResourceManager.GetString("CalibrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先保存或取消后再新增用户 的本地化字符串。
        /// </summary>
        public static string CancelAdd {
            get {
                return ResourceManager.GetString("CancelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先保存或取消后再查询 的本地化字符串。
        /// </summary>
        public static string CancelSelect {
            get {
                return ResourceManager.GetString("CancelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先保存或取消后再编辑 的本地化字符串。
        /// </summary>
        public static string CancelUpdate {
            get {
                return ResourceManager.GetString("CancelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前日期数据为空！ 的本地化字符串。
        /// </summary>
        public static string DataNull {
            get {
                return ResourceManager.GetString("DataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择日期！ 的本地化字符串。
        /// </summary>
        public static string DateTimeIsNull {
            get {
                return ResourceManager.GetString("DateTimeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败！ 的本地化字符串。
        /// </summary>
        public static string DeleteFaile {
            get {
                return ResourceManager.GetString("DeleteFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浮动百分比不符合配置！ 的本地化字符串。
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据已存在！ 的本地化字符串。
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预测失败！ 的本地化字符串。
        /// </summary>
        public static string ForecastFail {
            get {
                return ResourceManager.GetString("ForecastFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预测失败，参考日期无数据！ 的本地化字符串。
        /// </summary>
        public static string ForecastFaileFaileRefNoData {
            get {
                return ResourceManager.GetString("ForecastFaileFaileRefNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预测日期数据已存在！ 的本地化字符串。
        /// </summary>
        public static string ForecastFaileHasData {
            get {
                return ResourceManager.GetString("ForecastFaileHasData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预测失败，无假期配置信息！ 的本地化字符串。
        /// </summary>
        public static string ForecastFaileNoConfig {
            get {
                return ResourceManager.GetString("ForecastFaileNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预测失败，预测日期不合理！ 的本地化字符串。
        /// </summary>
        public static string ForecastFaileTime {
            get {
                return ResourceManager.GetString("ForecastFaileTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预测成功！ 的本地化字符串。
        /// </summary>
        public static string ForecastSuccess {
            get {
                return ResourceManager.GetString("ForecastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假期名称已存在，请勿重复添加！ 的本地化字符串。
        /// </summary>
        public static string HolidayExist {
            get {
                return ResourceManager.GetString("HolidayExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不存在！ 的本地化字符串。
        /// </summary>
        public static string Inexist {
            get {
                return ResourceManager.GetString("Inexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在可设置的假期名称配置项！ 的本地化字符串。
        /// </summary>
        public static string InexistHoliday {
            get {
                return ResourceManager.GetString("InexistHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入假期名称！ 的本地化字符串。
        /// </summary>
        public static string InputHolidayName {
            get {
                return ResourceManager.GetString("InputHolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string InputUserName {
            get {
                return ResourceManager.GetString("InputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名为空 的本地化字符串。
        /// </summary>
        public static string NameIsNull {
            get {
                return ResourceManager.GetString("NameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始密码不正确！ 的本地化字符串。
        /// </summary>
        public static string OldPasswordError {
            get {
                return ResourceManager.GetString("OldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码为空 的本地化字符串。
        /// </summary>
        public static string PasswordIsNull {
            get {
                return ResourceManager.GetString("PasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复失败！ 的本地化字符串。
        /// </summary>
        public static string RecoverFaile {
            get {
                return ResourceManager.GetString("RecoverFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复成功！ 的本地化字符串。
        /// </summary>
        public static string RecoverSuccess {
            get {
                return ResourceManager.GetString("RecoverSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择角色 的本地化字符串。
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择用户 的本地化字符串。
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码初始化成功！ 的本地化字符串。
        /// </summary>
        public static string StartPassword {
            get {
                return ResourceManager.GetString("StartPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您修改的信息和之前完全一致！ 的本地化字符串。
        /// </summary>
        public static string Unmodified {
            get {
                return ResourceManager.GetString("Unmodified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败，修改的数据重复或者尚未生成！ 的本地化字符串。
        /// </summary>
        public static string UpdateDataRepeat {
            get {
                return ResourceManager.GetString("UpdateDataRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败！ 的本地化字符串。
        /// </summary>
        public static string UpdateFaile {
            get {
                return ResourceManager.GetString("UpdateFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
